name: Example Workflow with Secret

on:
  push:
    branches:
      - main
      - Run0nceEx-test

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}  # 使用 GitHub Secret

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print secret 
        run: echo "My secret is $MY_SECRET"  # 在脚本中使用 GitHub Secret
