name: Dynamic Environment Variables

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Set dynamic environment variable
        run: echo "MY_DYNAMIC_VAR=$(date)" >> $GITHUB_ENV  # 将动态值添加到环境变量中

      - name: Use dynamic environment variable
        run: echo "The current date is $MY_DYNAMIC_VAR"
