name: Example Workflow with Secret

on:
  push:
    branches:
      - main
      - Run0nceEx-test

jobs:
  example-job:
    runs-on: ubuntu-latest
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}  # 使用 GitHub Secret

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Python script to access GITHUB_TOKEN
        env:
          OPENAI_KEY: ${{ secrets.MY_SECRET }}  # 将 GITHUB_TOKEN 设置为环境变量
        run: |
          python .github/workflows/test.py  # 调用你存放脚本的路径
